name: Artemis.Plugins.LayerBrushes.Particle - Build and upload

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/LayerBrushes/Artemis.Plugins.LayerBrushes.Particle/**'

jobs:
  upload:
    uses: ./.github/workflows/plugin-upload.yml
    with:
      projectPath: 'src/LayerBrushes/Artemis.Plugins.LayerBrushes.Particle/Artemis.Plugins.LayerBrushes.Particle.csproj'
    secrets:
      WORKSHOP_PAT: ${{ secrets.WORKSHOP_PAT }}

