name: Build and upload Artemis.Plugins.Audio

on:
  workflow_dispatch:
  push:
    branches:
      - feature/workshop-ci
    paths:
      - 'src/Collections/Artemis.Plugins.Audio/**'

jobs:
  upload:
    uses: ./.github/workflows/plugin-upload.yml
    with:
      projectPath: 'src/Collections/Artemis.Plugins.Audio/Artemis.Plugins.Audio.csproj'
      projectFolder: 'src/Collections/Artemis.Plugins.Audio'
      safeName: 'artemis-plugins-audio'
    secrets:
      WORKSHOP_PAT: ${{ secrets.WORKSHOP_PAT }}
