name: Build and upload Artemis.Plugins.Devices.Logitech

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/Devices/Artemis.Plugins.Devices.Logitech/**'

jobs:
  upload:
    uses: ./.github/workflows/plugin-upload.yml
    with:
      projectPath: 'src/Devices/Artemis.Plugins.Devices.Logitech/Artemis.Plugins.Devices.Logitech.csproj'
    secrets:
      WORKSHOP_PAT: ${{ secrets.WORKSHOP_PAT }}

