name: Build and upload Artemis.Plugins.Input

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/Collections/Artemis.Plugins.Input/**'

jobs:
  upload:
    uses: ./.github/workflows/plugin-upload.yml
    with:
      projectPath: 'src/Collections/Artemis.Plugins.Input/Artemis.Plugins.Input.csproj'
    secrets:
      WORKSHOP_PAT: ${{ secrets.WORKSHOP_PAT }}

