name: Build and upload Artemis.Plugins.Profiling

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/Other/Artemis.Plugins.Profiling/**'

jobs:
  upload:
    uses: ./.github/workflows/plugin-upload.yml
    with:
      projectPath: 'src/Other/Artemis.Plugins.Profiling/Artemis.Plugins.Profiling.csproj'
    secrets:
      WORKSHOP_PAT: ${{ secrets.WORKSHOP_PAT }}

