name: Artemis.Plugins.LayerEffects.LedReveal - Build and upload

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/LayerEffects/Artemis.Plugins.LayerEffects.LedReveal/**'

jobs:
  upload:
    uses: ./.github/workflows/plugin-upload.yml
    with:
      projectPath: 'src/LayerEffects/Artemis.Plugins.LayerEffects.LedReveal/Artemis.Plugins.LayerEffects.LedReveal.csproj'
    secrets:
      WORKSHOP_PAT: ${{ secrets.WORKSHOP_PAT }}

