name: Build and upload Artemis.Plugins.Modules.Processes

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/Modules/Artemis.Plugins.Modules.Processes/**'

jobs:
  upload:
    uses: ./.github/workflows/plugin-upload.yml
    with:
      projectPath: 'src/Modules/Artemis.Plugins.Modules.Processes/Artemis.Plugins.Modules.Processes.csproj'
    secrets:
      WORKSHOP_PAT: ${{ secrets.WORKSHOP_PAT }}

