name: Artemis.Plugins.Nodes.General - Build and upload

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/Nodes/Artemis.Plugins.Nodes.General/**'

jobs:
  upload:
    uses: ./.github/workflows/plugin-upload.yml
    with:
      projectPath: 'src/Nodes/Artemis.Plugins.Nodes.General/Artemis.Plugins.Nodes.General.csproj'
    secrets:
      WORKSHOP_PAT: ${{ secrets.WORKSHOP_PAT }}

