name: Artemis.Plugins.LayerBrushes.RemoteControl - Build and upload

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/LayerBrushes/Artemis.Plugins.LayerBrushes.RemoteControl/**'

jobs:
  upload:
    uses: ./.github/workflows/plugin-upload.yml
    with:
      projectPath: 'src/LayerBrushes/Artemis.Plugins.LayerBrushes.RemoteControl/Artemis.Plugins.LayerBrushes.RemoteControl.csproj'
    secrets:
      WORKSHOP_PAT: ${{ secrets.WORKSHOP_PAT }}

