name: Artemis.Plugins.Devices.Msi - Build and upload

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/Devices/Artemis.Plugins.Devices.Msi/**'

jobs:
  upload:
    uses: ./.github/workflows/plugin-upload.yml
    with:
      projectPath: 'src/Devices/Artemis.Plugins.Devices.Msi/Artemis.Plugins.Devices.Msi.csproj'
    secrets:
      WORKSHOP_PAT: ${{ secrets.WORKSHOP_PAT }}

